cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    thunt:
      email: tyler@vektirlabs.com
      name: Tyler Hunt
      password: $2b$12$ozzaNleAWPxxqItK89yqpu45YjFM.ojrfseUptxSKEhM2KSC4SHN
    thunt1:
      email: tyhunt82@gmail.com
      name: Tyler Hunt
      password: $2b$12$ozzaNleAWPxxqItK89yqpu45YjFM.ojrfseUptxSKEhM2KSC4SHN
preauthorized:
  emails:
  - tyler@vektirlabs.com
  - tyhunt82@gmail.com
