credentials:
  usernames:
    thunt:
      email: tyler@vektirlabs.com
      name: Tyler Hunt
      password: $2b$12$c4sTsgr4I.Waj1qvYNcPBuwKKz0oqCv0HocTunkQdX1SuchTgYEpy
    thunt1:
      email: tyhunt82@gmail.com
      name: Tyler Hunt
      password: $2b$12$oiomVA9j.8bXHo.W1pweAeJSaT4huDutHDnBQhz2x.pt71hYMTqoe
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - tyler@vektirlabs.com
  - tyhunt82@gmail.com