cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    thunt:
      email: tyler@vektirlabs.com
      name: Tyler Hunt
      password: $2b$12$shaWZbOVDeY8cx.fKT8XIeSzVzU53QiWdr5CgAYSVK3Ux2x.2CS/u
    thunt1:
      email: tyhunt82@gmail.com
      name: Tyler Hunt
      password: $2b$12$shaWZbOVDeY8cx.fKT8XIeSzVzU53QiWdr5CgAYSVK3Ux2x.2CS/u
preauthorized:
  emails:
  - tyler@vektirlabs.com
  - tyhunt82@gmail.com
